# Generated by Django 5.0.4 on 2026-09-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadb',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
